source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'figaro'
gem 'haml-rails'
gem 'devise', github: 'plataformatec/devise'
gem 'unicorn'
gem 'angularjs-rails'
gem 'bootstrap_form'
gem 'pry-rails'
gem 'pry'
gem 'hashie'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'moped'
gem 'mongoid_slug'
gem 'filepicker-rails'
gem 'exifr'
gem 'github_api'
gem 'sidekiq'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
end
