require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DaySummariesController do

  # This should return the minimal set of attributes required to create a valid
  # DaySummary. As you add validations to DaySummary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "day" => "2013-07-27" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DaySummariesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all day_summaries as @day_summaries" do
      day_summary = DaySummary.create! valid_attributes
      get :index, {}, valid_session
      assigns(:day_summaries).should eq([day_summary])
    end
  end

  describe "GET show" do
    it "assigns the requested day_summary as @day_summary" do
      day_summary = DaySummary.create! valid_attributes
      get :show, {:id => day_summary.to_param}, valid_session
      assigns(:day_summary).should eq(day_summary)
    end
  end

  describe "GET new" do
    it "assigns a new day_summary as @day_summary" do
      get :new, {}, valid_session
      assigns(:day_summary).should be_a_new(DaySummary)
    end
  end

  describe "GET edit" do
    it "assigns the requested day_summary as @day_summary" do
      day_summary = DaySummary.create! valid_attributes
      get :edit, {:id => day_summary.to_param}, valid_session
      assigns(:day_summary).should eq(day_summary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DaySummary" do
        expect {
          post :create, {:day_summary => valid_attributes}, valid_session
        }.to change(DaySummary, :count).by(1)
      end

      it "assigns a newly created day_summary as @day_summary" do
        post :create, {:day_summary => valid_attributes}, valid_session
        assigns(:day_summary).should be_a(DaySummary)
        assigns(:day_summary).should be_persisted
      end

      it "redirects to the created day_summary" do
        post :create, {:day_summary => valid_attributes}, valid_session
        response.should redirect_to(DaySummary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved day_summary as @day_summary" do
        # Trigger the behavior that occurs when invalid params are submitted
        DaySummary.any_instance.stub(:save).and_return(false)
        post :create, {:day_summary => { "day" => "invalid value" }}, valid_session
        assigns(:day_summary).should be_a_new(DaySummary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DaySummary.any_instance.stub(:save).and_return(false)
        post :create, {:day_summary => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested day_summary" do
        day_summary = DaySummary.create! valid_attributes
        # Assuming there are no other day_summaries in the database, this
        # specifies that the DaySummary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DaySummary.any_instance.should_receive(:update).with({ "day" => "2013-07-27" })
        put :update, {:id => day_summary.to_param, :day_summary => { "day" => "2013-07-27" }}, valid_session
      end

      it "assigns the requested day_summary as @day_summary" do
        day_summary = DaySummary.create! valid_attributes
        put :update, {:id => day_summary.to_param, :day_summary => valid_attributes}, valid_session
        assigns(:day_summary).should eq(day_summary)
      end

      it "redirects to the day_summary" do
        day_summary = DaySummary.create! valid_attributes
        put :update, {:id => day_summary.to_param, :day_summary => valid_attributes}, valid_session
        response.should redirect_to(day_summary)
      end
    end

    describe "with invalid params" do
      it "assigns the day_summary as @day_summary" do
        day_summary = DaySummary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DaySummary.any_instance.stub(:save).and_return(false)
        put :update, {:id => day_summary.to_param, :day_summary => { "day" => "invalid value" }}, valid_session
        assigns(:day_summary).should eq(day_summary)
      end

      it "re-renders the 'edit' template" do
        day_summary = DaySummary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DaySummary.any_instance.stub(:save).and_return(false)
        put :update, {:id => day_summary.to_param, :day_summary => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested day_summary" do
      day_summary = DaySummary.create! valid_attributes
      expect {
        delete :destroy, {:id => day_summary.to_param}, valid_session
      }.to change(DaySummary, :count).by(-1)
    end

    it "redirects to the day_summaries list" do
      day_summary = DaySummary.create! valid_attributes
      delete :destroy, {:id => day_summary.to_param}, valid_session
      response.should redirect_to(day_summaries_url)
    end
  end

end
